// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzO02-SSQANlAoL25xypC8AxyJYlEs5so',
    appId: '1:763536658683:web:cdd0ac29b25634981d205e',
    messagingSenderId: '763536658683',
    projectId: 'gsm-project-d158f',
    authDomain: 'gsm-project-d158f.firebaseapp.com',
    storageBucket: 'gsm-project-d158f.appspot.com',
    measurementId: 'G-BBC71PEK6L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADszS7bJsXJJglmjIjN9ir7KZAbSglqd8',
    appId: '1:763536658683:android:cfea1faf153e23cb1d205e',
    messagingSenderId: '763536658683',
    projectId: 'gsm-project-d158f',
    storageBucket: 'gsm-project-d158f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpo5t7fPlyG6V8Llb0JRKnfmzDXBi6Qc',
    appId: '1:763536658683:ios:77141f74db44188d1d205e',
    messagingSenderId: '763536658683',
    projectId: 'gsm-project-d158f',
    storageBucket: 'gsm-project-d158f.appspot.com',
    iosBundleId: 'com.example.gsmProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpo5t7fPlyG6V8Llb0JRKnfmzDXBi6Qc',
    appId: '1:763536658683:ios:77141f74db44188d1d205e',
    messagingSenderId: '763536658683',
    projectId: 'gsm-project-d158f',
    storageBucket: 'gsm-project-d158f.appspot.com',
    iosBundleId: 'com.example.gsmProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzO02-SSQANlAoL25xypC8AxyJYlEs5so',
    appId: '1:763536658683:web:30a863021a22c1e21d205e',
    messagingSenderId: '763536658683',
    projectId: 'gsm-project-d158f',
    authDomain: 'gsm-project-d158f.firebaseapp.com',
    storageBucket: 'gsm-project-d158f.appspot.com',
    measurementId: 'G-XNWWEX090X',
  );
}
